import { Geist, Geist_Mono, } from "next/font/google";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';

import "./globals.css";
import MainHeader from "./components/main-header";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const geist = Geist({ subsets: ['latin'] })
export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={GeistSans.className}>
        <div className="header">
          <div className="">

            <MainHeader />

            {children}


          </div>

        </div>




      </body>
    </html>
  );
}
